### Create new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "asfr@asdasda.com",
    "password": "hdasfas"
}

### Find a particular user with a given ID
GET http://localhost:3000/auth

### Find all users with a given email
GET http://localhost:3000/auth?email=sdada@asdasda.com

### Delete a user with a given id
DELETE http://localhost:3000/auth/6 

### Update a user
PATCH http://localhost:3000/auth/2
content-type: application/json

{
    "password": "password"
}


